### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by edosedgar** [komendart/diht2k18cpp#1]
So, I would say that I even didn't reach fuzz-test, everything ruined straight after compilation, 

$ g++ ./tests.cpp ./main.cpp 
In file included from ./main.cpp:2:0:
./solve_equation.h: In function ‘size_t solve_quadratic_equation(double, double, double, double&, double&, double)’:
./solve_equation.h:47:22: error: ‘assert’ was not declared in this scope
     assert(eps >= 0.0);

**Comment by komendart** [comment]
Now these files can be compiled.

**Comment by edosedgar** [comment]
Donezo, passed
